### ISSUE TITLE
Use this for todoist REST API

### ISSUE THREAD

**Issue by kaushalmodi** [vermiculus/apiwrap.el#2]
Thanks for developing this package.

I would like to develop an emacs interface to [Todoist][1]. I started working on [a todoist.el][2] package, but it's not going as fast as I'd like because of my inexperience with REST.

Is `apiwrap` general purpose enough to work for stuff like Todoist? Looks like it would allow me to do something like [this][3] easily?

[1]: https://todoist.com
[2]: https://github.com/kaushalmodi/todoist.el/blob/master/todoist.el
[3]: https://github.com/kaushalmodi/todoist.el/blob/37e8bba8327f5d452195df5ed85268b7f98536b9/todoist.el#L64-L70

**Comment by vermiculus** [comment]
API-Wrap is general-purpose, but it's a bit higher-level than your current implementation (and perhaps then, a bit opinionated). I will note that it was designed for REST APIs, and it doesn't look like Todoist uses that approach. API-Wrap doesn't really care, but the macro expressions will be a little more…awkward. For the macros to work, they need functions like `todoist-get`, `todoist-post`, etc. that each take three arguments:

- the resource to retrieve (which Todoist doesn't really use)
- post-URI parameters (like `/issues?state=all) as an alist (which Todoist doesn't use at all)
- data as an alist (which Todoist relies on for *everything*

It's worth noting that [every Todoist API request is done via POST](https://developer.todoist.com/#update-multiple-ordersindents31), so your get/post/put/patch/head/delete functions will all have the same implementation. (Or, if you're clever about it, you can just provide the 'post' function for all the methods needed by API-Wrap.)

I'm not *sure* (since I'm like a toddler with a hammer when it comes to cURL), but I think the request you linked to would be expressed as so

```elisp
(require 'json)

;;; You'll need to write this yourself;
;;; see tarsius/ghub for a good example.
;;; This is obviously just a stub.
(defun todoist-post (resource params data)
  (insert (format "POST\n  resource=%S\n  params=%s\n  data=%s"
                  resource
                  (json-encode params)
                  (json-encode data))))

;;; using the REST primitive by itself
;;; I'm trying to imitate the call you linked
(let ((todoist-api-token "fake-token"))
  (todoist-post "" nil
   `((token . ,todoist-api-token)
     (sync_token . "'*'")
     (resource_types . "'[\"all\"]'"))))
```

Now, with API-Wrap:
```elisp
(defun todoist--make-link (object)
  (concat "https://developer.todoist.com/#"
          (alist-get 'link object)))

(apiwrap-new-backend
 "Todoist" "todoist"
 nil
 :post #'todoist-post :get #'todoist-post :put #'todoist-post
 :patch #'todoist-post :delete #'todoist-post :head #'todoist-post
 :link #'todoist--make-link)

;; I could just as easily use the *get* variant;
;; use what makes sense for the resource.
;; They're all POSTs with this API anyway.
(defapipost-todoist "/unarchive-project"
  "Unarchive project and its children.
Only available for Todoist Premium users."
  "unarchive-a-project"
  ;; internal-resource is empty to avoid using the named resource
  nil "")

(defun todoist-project-unarchive (&rest IDs)
  (let ((uuid "some-uuid"))
    (todoist-post-unarchive-project
     `((type . project_unarchive)
       (uuid . ,uuid)
       (args (ids . IDs))))))
```

Now, running
```elisp
(todoist-project-unarchive "id1234" "id5678")
```
gives me
```
POST
  resource=""
  params=null
  data={"type":"project_unarchive","uuid":"some-uuid","args":{"ids":["id1234","id5678"]}}
```

One unrelated note: what you linked is not an alist (as in `todoist-project-unarchive`); it's just a normal list :wink:

---

All that said, I'm not sure API-Wrap will be of much help to you (since the API you want to use isn't really REST). What *would* be helpful for you is to learn the `json` support package (basically, just `json-encode` and `json-read-*`); this will make your syntax a bit cleaner.

**Comment by kaushalmodi** [comment]
I appreciate your detailed post! Let me resume my effort on that project this week.

> It's worth noting that every Todoist API request is done via POST,

Thanks, that just shows my ignorance about the API technologies used for data syncing between client/server. I thought it was REST API and the documentation used curl just for simplicity. Need to read up on POST vs REST..

> what you linked is not an alist

Of course, thanks for catching that :)

> What would be helpful for you is to learn the json support package (basically, just json-encode and json-read-*); this will make your syntax a bit cleaner.

Understood.

Thanks again!

**Comment by vermiculus** [comment]
Everybody learns it for the first time *some*time 😄

FYI, POST is an HTTP verb that's used by REST. REST is just a (popular) school of thought about how to leverage those verbs meaningfully.

Best of luck!
